[project]
name = "scryfall-telegram"
version = "2.6.1"
description = "Telegram bot backed by the Scryfall.com Magic:The Gathering API. Runs serverless."
readme = "README.md"
requires-python = ">= 3.13"
authors = [{ name = "Oliver Hofkens", email = "oliver@hofkens.eu" }]
dependencies = [
  "orjson>=3.11.5",
  "pyxdameraulevenshtein>=1.9.0",
  "requests>=2.32.5",
  "structlog>=25.5.0",
]

[dependency-groups]
dev = ["pytest>=9.0.3", "pytest-cov>=7.0.0", "ruff>=0.14.10"]

[tool.poe.tasks.lint]
sequence = [{ cmd = "ruff check" }, { cmd = "ruff format --check" }]

[tool.poe.tasks.test]
env = { ENV = "stag" }
cmd = "pytest tests/unit/ tests/integration/"

[tool.poe.tasks.package]
shell = """
rm -rf .build
mkdir .build
cp -R scryfall_telegram/ .build/scryfall_telegram
uv export --frozen --no-dev --no-editable --no-emit-project -o .build/requirements.txt
docker run --rm -v $(pwd):/home/app --workdir /home/app --platform linux/amd64 \
    rg.fr-par.scw.cloud/scwfunctionsruntimes-public/python-dep:3.13 \
    pip install \
    --target .build/package/ \
    -r .build/requirements.txt
"""

[tool.poe.tasks.deploy]
args = [{ name = "env", positional = true, default = "stag" }]
sequence = [
  { cmd = "terraform apply -state=$env.tfstate -var-file=$env.tfvars -var env=$env", cwd = "terraform" },
  { cmd = "scripts/register_webhook.py $env" },
]

[tool.pytest]
minversion = "9.0"
addopts = ["--tb=short", "--cov=.", "--cov-branch", "--cov-report=term-missing"]
testpaths = ["tests"]

[tool.uv.build-backend]
module-name = "scryfall_telegram"
module-root = ""

[build-system]
requires = ["uv_build>=0.9.21,<0.10.0"]
build-backend = "uv_build"
