[tool.poetry]
name = "scryfall-telegram"
version = "2.2.1"
description = ""
authors = ["Oliver Hofkens <oli.hofkens@gmail.com>"]
packages = [
    { include = "scryfall_telegram" }
]

[tool.poetry.dependencies]
python = "^3.8"

pyxDamerauLevenshtein = "1.7.0"
orjson = "^3.5.0"
requests = "^2.25.1"

black = { version = "==21.8b0", optional = true }
bump2version = { version = "^1.0.1", optional = true }
flake8 = { version = "^3.8", optional = true }
isort = { version = "^5.7", optional = true }
mypy = { version = "^0.800", optional = true }
pytest = { version = "^6.2", optional = true }
pytest-cov = { version = "*", optional = true }
vulture = { version = "^2.3", optional = true }
yamllint = { version = "^1.26.0", optional = true }

[tool.poetry.extras]
dev = ["bump2version"]
linting = ["flake8", "black", "isort", "mypy", "yamllint", "vulture"]
testing = ["pytest", "pytest-cov"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

