---
service: scryfall-telegram
variablesResolutionMode: "20210326"
configValidationMode: error

custom:
    currentStage: ${opt:stage, self:provider.stage}
    environments:
        staging: STAG
        production: PROD

    pythonRequirements:
        dockerizePip: non-linux
        slim: true

provider:
    name: aws
    runtime: python3.8
    region: eu-west-1
    memorySize: 128
    timeout: 25
    stage: staging

    environment:
        TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN_${self:custom.environments.${self:custom.currentStage}}}

plugins:
    - serverless-python-requirements
package:
    patterns:
        - "!**"
        - "scryfall_telegram/**"

functions:
    handle_telegram_webhook:
        handler: scryfall_telegram.handler.handle_telegram_webhook
        events:
            - httpApi:
                  path: /${env:WEBHOOK_SECRET}
                  method: POST
